[font]
size = 10

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 2

[font.normal]
family = "Hack"
style = "Regular"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[font.bold_italic]
family = "Hack"
style = "Bold Italic"

[colors.primary]
background = "#14161b"
foreground = "#ffffff"

[colors.cursor]
text = "#ffffff"
cursor = "#9b9ea4"

[colors.selection]
text = "#ffffff"
background = "#4f5258"

[colors.normal]
black = "#07080d"
red = "#ffa9a0"
green = "#9cf3ae"
yellow = "#ffdb77"
blue = "#8cd1ff"
magenta = "#ffb0ff"
cyan = "#6cfffd"
white = "#eef1f8"

[colors.bright]
black = "#4f5258"
red = "#ffc0b9"
green = "#b3f6c0"
yellow = "#fce094"
blue = "#a6dbff"
magenta = "#ffcaff"
cyan = "#8cf8f7"
white = "#ffffff"
