[font]
size = 10

[font.offset]
x = 0
y = 2

[font.glyph_offset]
x = 0
y = 1

[font.normal]
family = "MesloLGS Nerd Font Mono"
# family = "JetBrains Mono"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font Mono"
# family = "JetBrains Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
# family = "JetBrains Mono"
style = "Italic"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
# family = "JetBrains Mono"
style = "Bold Italic"

[keyboard]
bindings = [
  # Force CSI-u Shift+Return
  { key = "Enter", mods = "Shift", chars = "\u001b[13;2u" },
  # Force CSI-u Ctrl+.
  { key = ".", mods = "Control", chars = "\u001b[46;5u" },
]

[colors.primary]
background = "#14161b"
foreground = "#ffffff"

[colors.cursor]
text = "#ffffff"
cursor = "#9b9ea4"

[colors.selection]
text = "#ffffff"
background = "#4f5258"

[colors.normal]
black = "#07080d"
red = "#ffa9a0"
green = "#9cf3ae"
yellow = "#ffdb77"
blue = "#8cd1ff"
magenta = "#ffb0ff"
cyan = "#6cfffd"
white = "#eef1f8"

[colors.bright]
black = "#4f5258"
red = "#ffc0b9"
green = "#b3f6c0"
yellow = "#fce094"
blue = "#a6dbff"
magenta = "#ffcaff"
cyan = "#8cf8f7"
white = "#ffffff"
