return {}

-- return {
-- 	"mrcjkb/rustaceanvim",
-- 	lazy = false, -- this plugin is already lazy
-- 	config = function()
-- 		vim.g.rustaceanvim = {
-- 			server = {
-- 				default_settings = {
-- 					["rust-analyzer"] = {
-- 						cargo = {
-- 							allFeatures = true,
-- 						},
-- 						check = {
-- 							command = "clippy",
-- 						},
-- 					},
-- 				},
-- 			},
-- 		}
-- 	end,
-- }
