require('options')
require('plugins')
require('keymaps')
require('theme.onedark')
require('tree')
require('line')
require('telescope_setup')
require('treesitter_setup')
require('lsp')
require('startup')

