require("options")
require("plugins")
require("keymaps")
require("theme.onedark")
require("tree")
require("line")
require("telescope_setup")
require("treesitter_setup")
require("lsp")
require("git")
require("comment_setup")
require("autopair")
require("color_preview")
require("line_indent")
require("lint")
require("startup")

